import Link from "next/link";
import { requireCompanyContext } from "@/lib/auth/session";
import { listMemoriesForUser } from "@/lib/orqena/memory-service";
import { changeMemory } from "./actions";
import { CompactFilterBar, CompactSearch, ResultCount } from "@/components/ui-primitives";

export default async function MemorySettingsPage({ searchParams }: { searchParams: Promise<{ q?: string; estado?: string }> }) {
  const auth = await requireCompanyContext();
  const query = await searchParams;
  const memories = await listMemoriesForUser({ companyId: auth.companyId, userId: auth.userId, q: query.q, status: query.estado });
  return <main className="screen"><header className="mb-5"><Link href="/configuracion" className="text-sm text-muted">← Configuración</Link><h1 className="type-page-title mt-2">Memoria de Orqena</h1><p className="type-secondary mt-2">Revisa la memoria disponible para tu cuenta. Los recuerdos originados en chats de otras personas nunca aparecen aquí.</p></header><CompactFilterBar className="mb-4"><form className="flex gap-2"><CompactSearch name="q" defaultValue={query.q} placeholder="Buscar recuerdos…"/><select className="field max-w-48" name="estado" defaultValue={query.estado ?? ""}><option value="">Todos</option><option value="SUGGESTED">Sugerencias</option><option value="CONFIRMED">Confirmados</option><option value="ARCHIVED">Archivados</option></select><button className="secondary-button">Filtrar</button></form></CompactFilterBar><ResultCount shown={memories.length} total={memories.length} noun="recuerdos"/><div className="mt-4 grid gap-2">{memories.map((memory) => <article key={memory.id} className="rounded-xl border border-border bg-surface p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold text-content">{memory.summary}</p><p className="type-meta mt-1">{memory.category} · {memory.updatedAt.toLocaleDateString("es-ES")}</p>{memory.sourceConversationId ? <Link className="mt-2 inline-block text-sm underline" href={`/capataz?conversationId=${memory.sourceConversationId}`}>Abrir conversación de origen</Link> : null}</div><form action={changeMemory} className="flex flex-wrap gap-2"><input type="hidden" name="id" value={memory.id}/>{memory.status === "SUGGESTED" ? <><button name="action" value="confirm" className="primary-button">Confirmar</button><button name="action" value="reject" className="secondary-button">Rechazar</button></> : null}{memory.status !== "ARCHIVED" ? <button name="action" value="archive" className="secondary-button">Archivar</button> : null}</form></div></article>)}{!memories.length ? <div className="rounded-xl border border-dashed border-border p-8 text-center"><h2 className="font-semibold">Aún no hay recuerdos en esta vista</h2></div> : null}</div></main>;
}
