-- Additive ownership columns. They remain nullable until backfill reconciliation is complete.
ALTER TABLE "Client" ADD COLUMN "companyId" TEXT;
ALTER TABLE "Contact" ADD COLUMN "companyId" TEXT;
ALTER TABLE "Work" ADD COLUMN "companyId" TEXT;
ALTER TABLE "Budget" ADD COLUMN "companyId" TEXT;
ALTER TABLE "Invoice" ADD COLUMN "companyId" TEXT;
ALTER TABLE "Payment" ADD COLUMN "companyId" TEXT;
ALTER TABLE "Expense" ADD COLUMN "companyId" TEXT;
ALTER TABLE "Material" ADD COLUMN "companyId" TEXT;
ALTER TABLE "Document" ADD COLUMN "companyId" TEXT;
ALTER TABLE "InternalNote" ADD COLUMN "companyId" TEXT;
ALTER TABLE "Reminder" ADD COLUMN "companyId" TEXT;
ALTER TABLE "EventoAgenda" ADD COLUMN "companyId" TEXT;
ALTER TABLE "Notification" ADD COLUMN "companyId" TEXT;
ALTER TABLE "FinancialAccount" ADD COLUMN "companyId" TEXT;
ALTER TABLE "CashMovement" ADD COLUMN "companyId" TEXT;
ALTER TABLE "RecurringExpense" ADD COLUMN "companyId" TEXT;
ALTER TABLE "ExpectedCashFlow" ADD COLUMN "companyId" TEXT;
ALTER TABLE "ChatConversation" ADD COLUMN "companyId" TEXT;
ALTER TABLE "BusinessSignalState" ADD COLUMN "companyId" TEXT;
ALTER TABLE "BusinessRecommendation" ADD COLUMN "companyId" TEXT;
ALTER TABLE "AutomationRun" ADD COLUMN "companyId" TEXT;

CREATE INDEX "Client_companyId_idx" ON "Client"("companyId");
CREATE INDEX "Contact_companyId_idx" ON "Contact"("companyId");
CREATE INDEX "Work_companyId_idx" ON "Work"("companyId");
CREATE INDEX "Budget_companyId_idx" ON "Budget"("companyId");
CREATE INDEX "Invoice_companyId_idx" ON "Invoice"("companyId");
CREATE INDEX "Payment_companyId_idx" ON "Payment"("companyId");
CREATE INDEX "Expense_companyId_idx" ON "Expense"("companyId");
CREATE INDEX "Material_companyId_idx" ON "Material"("companyId");
CREATE INDEX "Document_companyId_idx" ON "Document"("companyId");
CREATE INDEX "InternalNote_companyId_idx" ON "InternalNote"("companyId");
CREATE INDEX "Reminder_companyId_idx" ON "Reminder"("companyId");
CREATE INDEX "EventoAgenda_companyId_idx" ON "EventoAgenda"("companyId");
CREATE INDEX "Notification_companyId_idx" ON "Notification"("companyId");
CREATE INDEX "FinancialAccount_companyId_idx" ON "FinancialAccount"("companyId");
CREATE INDEX "CashMovement_companyId_idx" ON "CashMovement"("companyId");
CREATE INDEX "RecurringExpense_companyId_idx" ON "RecurringExpense"("companyId");
CREATE INDEX "ExpectedCashFlow_companyId_idx" ON "ExpectedCashFlow"("companyId");
CREATE INDEX "ChatConversation_companyId_idx" ON "ChatConversation"("companyId");
CREATE INDEX "BusinessSignalState_companyId_idx" ON "BusinessSignalState"("companyId");
CREATE INDEX "BusinessRecommendation_companyId_idx" ON "BusinessRecommendation"("companyId");
CREATE INDEX "AutomationDefinition_companyId_idx" ON "AutomationDefinition"("companyId");
CREATE INDEX "AutomationRun_companyId_idx" ON "AutomationRun"("companyId");
CREATE INDEX "Task_companyId_idx" ON "Task"("companyId");
CREATE INDEX "FollowUp_companyId_idx" ON "FollowUp"("companyId");

ALTER TABLE "Client" ADD CONSTRAINT "Client_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Contact" ADD CONSTRAINT "Contact_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Work" ADD CONSTRAINT "Work_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Budget" ADD CONSTRAINT "Budget_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Material" ADD CONSTRAINT "Material_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Document" ADD CONSTRAINT "Document_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InternalNote" ADD CONSTRAINT "InternalNote_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Reminder" ADD CONSTRAINT "Reminder_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EventoAgenda" ADD CONSTRAINT "EventoAgenda_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FinancialAccount" ADD CONSTRAINT "FinancialAccount_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CashMovement" ADD CONSTRAINT "CashMovement_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecurringExpense" ADD CONSTRAINT "RecurringExpense_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ExpectedCashFlow" ADD CONSTRAINT "ExpectedCashFlow_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ChatConversation" ADD CONSTRAINT "ChatConversation_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "BusinessSignalState" ADD CONSTRAINT "BusinessSignalState_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "BusinessRecommendation" ADD CONSTRAINT "BusinessRecommendation_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AutomationDefinition" ADD CONSTRAINT "AutomationDefinition_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AutomationRun" ADD CONSTRAINT "AutomationRun_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FollowUp" ADD CONSTRAINT "FollowUp_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
