import Link from "next/link";
import { requirePlatformAccount } from "@/lib/commercial/platform";
import { prisma } from "@/lib/prisma";
import { buildPlatformHealthSnapshot } from "@/lib/product/metrics";
import { savePilotCohort, saveProductExperiment, saveServiceCost, updateSupportTicket } from "../actions";

export const dynamic = "force-dynamic";

export default async function PlatformHealthPage() {
  await requirePlatformAccount("PLATFORM_OWNER");
  const [snapshot, companies, tickets, cohorts, experiments] = await Promise.all([
    buildPlatformHealthSnapshot(prisma),
    prisma.company.findMany({ where: { archivedAt: null, isDemo: false }, select: { id: true, nombreComercial: true }, orderBy: { createdAt: "asc" }, take: 100 }),
    prisma.supportTicket.findMany({ select: { id: true, companyId: true, status: true, priority: true, firstResponseDueAt: true, resolutionDueAt: true, supportMinutes: true }, orderBy: { createdAt: "desc" }, take: 30 }),
    prisma.pilotCohort.findMany({ select: { id: true, status: true, paid: true, contractStatus: true, consentStatus: true, resultStatus: true, cadence: true }, orderBy: { createdAt: "desc" }, take: 30 }),
    prisma.productExperiment.findMany({ orderBy: { createdAt: "desc" }, take: 30 }),
  ]);
  const now = new Date();
  const start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString().slice(0, 10);
  const end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1)).toISOString().slice(0, 10);
  return <main className="screen"><Link href="/plataforma" className="text-sm text-muted">← Plataforma interna</Link><h1 className="type-page-title mt-2">Salud de producto y pilotos</h1><p className="type-secondary mt-2">Vista agregada PLATFORM_OWNER. Calculada {snapshot.calculatedAt.toLocaleString("es-ES")} con metodología {snapshot.methodologyVersion}; no muestra prompts, tickets, documentos ni contenido de tenants.</p>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Activación ≤7 días" value={percent(snapshot.activation.rate)}/><Metric label="WAU usuarios / empresas" value={`${snapshot.wau.users} / ${snapshot.wau.companies}`}/><Metric label="MRR reconciliado" value={money(snapshot.commercial.mrrEur)}/><Metric label="Margen bruto verificado" value={snapshot.economics.grossMarginRate === null ? "Sin base real" : percent(snapshot.economics.grossMarginRate)}/><Metric label="Conversión de presupuestos" value={percent(snapshot.value.budgetConversionRate)}/><Metric label="Plazo medio de cobro" value={snapshot.value.averageCollectionDays === null ? "Sin datos" : `${snapshot.value.averageCollectionDays.toFixed(1)} días`}/><Metric label="Deuda recuperada" value={money(snapshot.value.recoveredDebtEur)}/><Metric label="Tiempo ahorrado" value={`${Math.round(snapshot.value.minutesSaved / 60)} h`}/></section>
    <section className="card mt-6 p-5"><h2 className="type-section-title">Retención y coste de servir</h2><div className="mt-3 grid gap-3 sm:grid-cols-3">{snapshot.retention.map((item) => <Metric key={item.month} label={`${item.month} (${item.eligible} elegibles)`} value={percent(item.rate)}/>)}</div><p className="type-secondary mt-3">Coste verificado {money(snapshot.economics.verifiedCostEur)} · soporte {snapshot.support.hours.toFixed(1)} h · IA {snapshot.ai.calls} operaciones / {money(snapshot.ai.costEur)}. Los estados locales simulados no contribuyen al MRR.</p></section>
    <section className="mt-8 grid gap-4 xl:grid-cols-3"><form action={savePilotCohort} className="card grid gap-3 p-5"><h2 className="type-section-title">Cohorte piloto</h2><CompanySelect companies={companies}/><input className="field" name="cohortKey" placeholder="pilot-2026-01" required/><div className="grid grid-cols-2 gap-2"><select aria-label="Estado de la cohorte" className="field" name="status"><option>PLANNED</option><option>ONBOARDING</option><option>ACTIVE</option><option>PAUSED</option><option>COMPLETED</option><option>WITHDRAWN</option></select><input aria-label="Fecha de inicio de la cohorte" className="field" type="date" name="startsAt" defaultValue={start} required/></div><div className="grid grid-cols-2 gap-2"><select aria-label="Estado del contrato" className="field" name="contractStatus"><option>NOT_RECORDED</option><option>DRAFT</option><option>SIGNED</option><option>EXPIRED</option></select><select aria-label="Estado del consentimiento" className="field" name="consentStatus"><option>NOT_RECORDED</option><option>REQUESTED</option><option>GRANTED</option><option>WITHDRAWN</option></select></div><select aria-label="Cadencia de seguimiento" className="field" name="cadence"><option>WEEKLY</option><option>FORTNIGHTLY</option></select><label className="flex gap-2"><input type="checkbox" name="paid"/>Piloto de pago verificado</label><textarea className="field" name="goals" placeholder="Objetivos separados por coma" required/><textarea className="field" name="successCriteria" placeholder="Criterios medibles separados por coma" required/><input className="field" name="commercialSummary" placeholder="Resumen comercial minimizado"/><input className="field" name="supportNeeds" placeholder="Necesidad de soporte"/><input className="field" name="productFocus" placeholder="Foco de producto"/><button className="primary-button">Guardar cohorte</button></form>
      <form action={saveServiceCost} className="card grid content-start gap-3 p-5"><h2 className="type-section-title">Coste de servir</h2><CompanySelect companies={companies}/><div className="grid grid-cols-2 gap-2"><input aria-label="Inicio del periodo de coste" className="field" type="date" name="periodStart" defaultValue={start} required/><input aria-label="Fin del periodo de coste" className="field" type="date" name="periodEnd" defaultValue={end} required/></div><select aria-label="Categoría del coste" className="field" name="category"><option>INFRASTRUCTURE</option><option>AI</option><option>STORAGE</option><option>EMAIL</option><option>SUPPORT</option></select><input className="field" name="amount" type="number" min="0" step="0.000001" placeholder="EUR" required/><select aria-label="Tipo de fuente del coste" className="field" name="sourceType"><option>PROVIDER_INVOICE</option><option>MEASURED_USAGE</option><option>TIME_LOG</option></select><input className="field" name="sourceReference" placeholder="Referencia de evidencia (se guarda hash)" required/><input className="field" name="planKey" placeholder="Plan opcional"/><label className="flex gap-2"><input type="checkbox" name="verified"/>Fuente verificada</label><button className="primary-button">Registrar coste</button></form>
      <form action={saveProductExperiment} className="card grid content-start gap-3 p-5"><h2 className="type-section-title">Experimento y decisión</h2><input className="field" name="experimentKey" placeholder="onboarding-checklist-v1" required/><select aria-label="Área del experimento" className="field" name="area"><option>ONBOARDING</option><option>PRICING</option><option>PRODUCT</option></select><textarea className="field" name="hypothesis" placeholder="Si hacemos X, mejorará Y porque Z" required/><input className="field" name="primaryMetric" placeholder="Métrica primaria" required/><textarea className="field" name="guardrails" placeholder="Guardrails separados por coma" required/><select aria-label="Estado del experimento" className="field" name="status"><option>DRAFT</option><option>RUNNING</option><option>DECIDED</option><option>STOPPED</option></select><textarea className="field" name="decision" placeholder="Decisión y motivo"/><button className="primary-button">Guardar experimento</button></form></section>
    <section className="mt-8"><h2 className="type-section-title">Soporte con SLA y tiempo</h2><div className="mt-3 grid gap-3">{tickets.map((ticket) => <form action={updateSupportTicket} className="card grid gap-2 p-4 md:grid-cols-[1fr_1fr_1fr_1fr_auto]" key={ticket.id}><input type="hidden" name="ticketId" value={ticket.id}/><input type="hidden" name="companyId" value={ticket.companyId}/><div><strong>Ticket {ticket.id.slice(-8)}</strong><p className="type-meta">{ticket.priority} · {ticket.supportMinutes} min · respuesta {ticket.firstResponseDueAt?.toLocaleString("es-ES") ?? "—"}</p></div><select aria-label={`Estado del ticket ${ticket.id.slice(-8)}`} className="field" name="status" defaultValue={ticket.status}><option>OPEN</option><option>IN_PROGRESS</option><option>WAITING_CUSTOMER</option><option>RESOLVED</option><option>CLOSED</option></select><input aria-label={`Minutos de soporte para el ticket ${ticket.id.slice(-8)}`} className="field" name="minutes" type="number" min="0" max="480" defaultValue="0"/><select aria-label={`Resolución del ticket ${ticket.id.slice(-8)}`} className="field" name="resolutionCode" defaultValue=""><option value="">Sin resolución</option><option>GUIDANCE</option><option>CONFIGURATION</option><option>DEFECT</option><option>FEATURE_REQUEST</option><option>ACCESS_RECOVERY</option><option>NO_ACTION</option></select><button className="secondary-button">Actualizar</button></form>)}{!tickets.length ? <p className="empty-state">No hay tickets.</p> : null}</div></section>
    <section className="mt-8 grid gap-4 lg:grid-cols-2"><div className="card p-5"><h2 className="type-section-title">Pilotos</h2><p className="type-secondary mt-2">{cohorts.length} registrados · {cohorts.filter((item) => item.paid).length} de pago · {cohorts.filter((item) => item.contractStatus === "SIGNED" && item.consentStatus === "GRANTED").length} con contrato y consentimiento.</p></div><div className="card p-5"><h2 className="type-section-title">Experimentos</h2><p className="type-secondary mt-2">{experiments.length} registrados · {experiments.filter((item) => item.status === "RUNNING").length} activos · {experiments.filter((item) => item.status === "DECIDED").length} decididos.</p></div></section>
  </main>;
}
function Metric({ label, value }: { label: string; value: string }) { return <article className="card p-4"><p className="type-meta">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></article>; }
function CompanySelect({ companies }: { companies: Array<{ id: string; nombreComercial: string }> }) { return <select aria-label="Empresa" className="field" name="companyId" required>{companies.map((company) => <option value={company.id} key={company.id}>{company.nombreComercial}</option>)}</select>; }
function percent(value: number | null) { return value === null ? "Sin base" : new Intl.NumberFormat("es-ES", { style: "percent", maximumFractionDigits: 1 }).format(value); }
function money(value: number) { return new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(value); }
