"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { Filter, Search, SlidersHorizontal, X } from "lucide-react";

export function CompactSearch({ name = "buscar", defaultValue = "", placeholder = "Buscar…" }: { name?: string; defaultValue?: string; placeholder?: string }) { return <label className="relative min-w-0 flex-1"><span className="sr-only">Buscar</span><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted" size={18}/><input className="field min-h-11 pl-10" type="search" name={name} defaultValue={defaultValue} placeholder={placeholder}/></label>; }
export function FilterCount({ count }: { count: number }) { return count ? <span className="rounded-full bg-content px-1.5 py-0.5 text-[11px] tabular-nums text-white" aria-label={`${count} filtros activos`}>{count}</span> : null; }
export function FilterTrigger({ count, onClick }: { count: number; onClick: () => void }) { return <button type="button" className="secondary-button min-h-11 shrink-0" onClick={onClick} aria-haspopup="dialog"><Filter size={18}/><span>Filtros</span><FilterCount count={count}/></button>; }
export function SortTrigger({ children }: { children?: ReactNode }) { return <button className="secondary-button hidden min-h-11 md:inline-flex" type="button"><SlidersHorizontal size={18}/>{children ?? "Ordenar"}</button>; }
export function ActiveFilterChips({ filters, onRemove }: { filters: Array<{ key: string; label: string }>; onRemove?: (key: string) => void }) { return filters.length ? <div className="flex flex-wrap gap-2" aria-label="Filtros activos">{filters.map((item) => <button type="button" key={item.key} className="inline-flex min-h-9 items-center gap-1 rounded-full bg-surface-secondary px-3 text-sm" onClick={() => onRemove?.(item.key)}>{item.label}<X size={14}/><span className="sr-only">Quitar filtro</span></button>)}</div> : null; }
export function FilterSheet({ open, title = "Filtros", children, onClose, onClear }: { open: boolean; title?: string; children: ReactNode; onClose: () => void; onClear?: () => void }) {
  const panel = useRef<HTMLDivElement>(null); const opener = useRef<HTMLElement | null>(null);
  useEffect(() => { if (!open) return; opener.current = document.activeElement as HTMLElement; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; panel.current?.focus(); const close = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.addEventListener("keydown", close); return () => { document.body.style.overflow = previous; document.removeEventListener("keydown", close); opener.current?.focus(); }; }, [open, onClose]);
  if (!open) return null;
  return <div className="fixed inset-0 z-50 bg-black/35 md:flex md:items-center md:justify-center" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div ref={panel} role="dialog" aria-modal="true" aria-labelledby="filter-sheet-title" tabIndex={-1} className="absolute inset-x-0 bottom-0 max-h-[85dvh] overflow-y-auto rounded-t-2xl bg-surface p-4 pb-[max(1rem,env(safe-area-inset-bottom))] shadow-xl outline-none md:static md:w-[520px] md:rounded-2xl"><header className="mb-4 flex items-center justify-between"><h2 id="filter-sheet-title" className="type-section-title">{title}</h2><button type="button" className="icon-button" onClick={onClose} aria-label="Cerrar filtros"><X/></button></header>{children}<footer className="sticky bottom-0 mt-5 flex gap-2 bg-surface py-2"><button type="button" className="secondary-button flex-1" onClick={onClear}>Limpiar</button><button type="button" className="primary-button flex-1" onClick={onClose}>Aplicar</button></footer></div></div>;
}
