import Link from "next/link";
import { CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, ExternalLink, FileCheck2, FileText, Search, SlidersHorizontal, Upload, WalletCards } from "lucide-react";
import { PurchaseInvoiceRailContext } from "@/components/portal/purchase-invoice-rail-context";
import type { PurchaseAccess } from "@/lib/commercial/purchase-access";
import { purchaseRelationAllowed } from "@/lib/commercial/purchase-access";
import { getPurchaseInvoiceDetail, getPurchaseInvoiceList } from "@/lib/procurement";
import base from "./supplier-invoice-directory-v2.module.css";
import styles from "./subcontractor-invoice-directory-v2.module.css";

type QueryRecord = Record<string, string | string[] | undefined>;
type Invoice = Awaited<ReturnType<typeof getPurchaseInvoiceList>>[number];

export async function SubcontractorInvoiceDirectoryV2({ companyId, searchParams, access, canExport }: { companyId: string; searchParams: Promise<QueryRecord>; access: PurchaseAccess; canExport: boolean }) {
  const raw = await searchParams;
  const all = await getPurchaseInvoiceList(companyId, "SUBCONTRACTOR");
  const scoped = all.filter((invoice) => purchaseRelationAllowed(access.read, invoice.workId, invoice.expense?.clienteId));
  const filtered = scoped.filter((invoice) => matches(invoice, raw));
  const pageSize = 8;
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize));
  const page = Math.min(pageCount, Math.max(1, numberValue(raw.pagina, 1)));
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  const selectedListItem = visible.find((invoice) => invoice.id === first(raw.seleccion)) ?? visible[0] ?? null;
  const detail = selectedListItem ? await getPurchaseInvoiceDetail(companyId, selectedListItem.id, "SUBCONTRACTOR") : null;
  const selected = detail && purchaseRelationAllowed(access.read, detail.workId, detail.expense?.clienteId) ? detail : null;
  const panel = ["detalle", "documento", "historial"].includes(first(raw.panel) ?? "") ? first(raw.panel)! : "detalle";
  const metrics = metricValues(scoped);
  const canCreate = access.manage.allowed && (access.manage.scope === "COMPANY" || scoped.some((invoice) => purchaseRelationAllowed(access.manage, invoice.workId, invoice.expense?.clienteId)));
  const canPaySelected = Boolean(selected && purchaseRelationAllowed(access.pay, selected.workId, selected.expense?.clienteId));
  const attention = scoped.filter((invoice) => !invoice.documents.length && invoice.status !== "VOID").slice(0, 3).map((invoice) => ({ id: invoice.id, title: invoice.invoiceNumber, detail: `${invoice.businessPartner.commercialName} · ${formatCurrency(invoice.total)}`, href: `/facturas-subcontratas?seleccion=${encodeURIComponent(invoice.id)}#directorio` }));

  return <main className={base.page} data-subcontractor-invoice-workspace>
    <PurchaseInvoiceRailContext value={{ kind: "subcontractor", visibleCount: scoped.length, reviewCount: metrics.review.count, overdueCount: metrics.overdue.count, overdueAmount: metrics.overdue.amount, pendingAmount: metrics.pending.amount, unassignedCount: scoped.filter((invoice) => !invoice.workId && invoice.status !== "VOID").length, retentionAmount: metrics.retention, upcomingCount: scoped.filter(isUpcoming).length, attention }} />

    <header className={base.header}><div><h1>Facturas subcontrata</h1><p>Gestiona y valida las facturas recibidas de subcontratistas con trazabilidad de obra, certificación y pago.</p></div><div className={styles.headerActions}>{canExport ? <Link className={base.secondaryButton} href={exportHref(raw)}><Download size={14} />Exportar</Link> : null}{canCreate ? <Link className={base.secondaryButton} href="/gastos-materiales/lector"><Upload size={14} />Subir factura</Link> : null}<details className={base.moreFilters}><summary><SlidersHorizontal size={14} />Más filtros</summary><FilterPanel raw={raw} /></details></div></header>

    <nav className={styles.tabs} aria-label="Estados de facturas de subcontrata">
      <Tab raw={raw} value="all" label="Todas" count={scoped.length} />
      <Tab raw={raw} value="revision" label="Pendientes de revisión" count={metrics.review.count} />
      <Tab raw={raw} value="pendiente" label="Pendientes de pago" count={metrics.pending.count} />
      <Tab raw={raw} value="revisada" label="Revisadas" count={metrics.reviewed.count} />
      <Tab raw={raw} value="anulada" label="Anuladas" count={metrics.voided.count} />
      <Tab raw={raw} value="pagada" label="Pagadas" count={metrics.paidAll.count} />
    </nav>

    <section className={base.metrics} aria-label="Indicadores de facturas de subcontrata">
      <Metric icon={<FileText size={16} />} label="Total facturas (mes)" value={formatCurrency(metrics.month.amount)} note={`${metrics.month.count} facturas`} tone="info" href={hrefWith(raw, { estado: "all", pagina: null })} />
      <Metric icon={<Clock3 size={16} />} label="Pendientes de revisión" value={String(metrics.review.count)} note={formatCurrency(metrics.review.amount)} tone="warning" href={hrefWith(raw, { estado: "revision", pagina: null })} />
      <Metric icon={<WalletCards size={16} />} label="Pendientes de pago" value={String(metrics.pending.count)} note={formatCurrency(metrics.pending.amount)} tone="warning" href={hrefWith(raw, { estado: "pendiente", pagina: null })} />
      <Metric icon={<CheckCircle2 size={16} />} label="Revisadas" value={String(metrics.reviewed.count)} note={formatCurrency(metrics.reviewed.amount)} tone="success" href={hrefWith(raw, { estado: "revisada", pagina: null })} />
      <Metric icon={<FileCheck2 size={16} />} label="Retenciones fiscales" value={formatCurrency(-metrics.retention)} note={`Sobre ${metrics.retentionCount} facturas`} tone="info" href={hrefWith(raw, { retencion: "1", pagina: null })} />
    </section>

    <section id="directorio" className={`${base.workspace} ${styles.workspace}`} aria-label="Facturas de subcontrata y detalle">
      <div className={base.listPane}>{visible.length ? <>
        <div className={base.tableScroll}><table className={`${base.table} ${styles.table}`}><thead><tr><th>Factura</th><th>Subcontratista</th><th>Proyecto</th><th>Certificación / Partida</th><th>Importe sin IVA</th><th>IVA</th><th>Estado revisión</th><th>Retención fiscal</th><th>Vencimiento</th><th>Estado pago</th></tr></thead><tbody>{visible.map((invoice) => <InvoiceRow key={invoice.id} invoice={invoice} raw={raw} selected={selectedListItem?.id === invoice.id} />)}</tbody></table></div>
        <div className={base.mobileList}>{visible.map((invoice) => <MobileInvoice key={invoice.id} invoice={invoice} raw={raw} selected={selectedListItem?.id === invoice.id} />)}</div>
        <footer className={base.tableFooter}><span>{(page - 1) * pageSize + 1}–{Math.min(page * pageSize, filtered.length)} de {filtered.length} facturas</span><nav aria-label="Paginación">{page > 1 ? <Link href={hrefWith(raw, { pagina: String(page - 1), seleccion: null })} aria-label="Página anterior"><ChevronLeft size={14} /></Link> : <span><ChevronLeft size={14} /></span>}<strong>{page}</strong>{page < pageCount ? <Link href={hrefWith(raw, { pagina: String(page + 1), seleccion: null })} aria-label="Página siguiente"><ChevronRight size={14} /></Link> : <span><ChevronRight size={14} /></span>}</nav></footer>
      </> : <div className={base.empty}><FileText size={28} /><h2>No hay facturas de subcontrata con estos criterios</h2><p>La estructura queda preparada para datos reales; no se generan registros de demostración.</p>{canCreate ? <Link className={base.primaryButton} href="/gastos-materiales/lector">Subir factura</Link> : null}</div>}</div>

      <aside className={base.detailPane} aria-label="Detalle de factura de subcontrata">{selected ? <InvoiceDetail invoice={selected} raw={raw} panel={panel} canPay={canPaySelected} /> : <div className={base.detailEmpty}><FileCheck2 size={30} /><h2>Selecciona una factura</h2><p>Revisa certificación, importes, documento, historial y pago sin salir de la lista.</p></div>}</aside>
    </section>
  </main>;
}

function FilterPanel({ raw }: { raw: QueryRecord }) { return <form className={styles.filterPanel} action="/facturas-subcontratas" method="get"><label><span>Buscar</span><span className={styles.search}><Search size={13} /><input name="buscar" defaultValue={first(raw.buscar) ?? ""} placeholder="Factura, subcontrata o proyecto…" /></span></label><label><input type="checkbox" name="sinObra" value="1" defaultChecked={first(raw.sinObra) === "1"} /> Sin proyecto asignado</label><label><input type="checkbox" name="conDocumento" value="1" defaultChecked={first(raw.conDocumento) === "1"} /> Con documento adjunto</label><label><input type="checkbox" name="retencion" value="1" defaultChecked={first(raw.retencion) === "1"} /> Con retención fiscal</label><button className={base.primaryButton} type="submit">Aplicar filtros</button></form>; }
function Tab({ raw, value, label, count }: { raw: QueryRecord; value: string; label: string; count: number }) { const active = (first(raw.estado) ?? "all") === value; return <Link href={hrefWith(raw, { estado: value, pagina: null, seleccion: null })} aria-current={active ? "page" : undefined}>{label}{count ? <span>{count}</span> : null}</Link>; }
function Metric({ icon, label, value, note, tone, href }: { icon: React.ReactNode; label: string; value: string; note: string; tone: string; href: string }) { return <Link href={href} className={base.metric} data-tone={tone}><span className={base.metricIcon}>{icon}</span><span><small>{label}</small><strong>{value}</strong><em>{note}</em></span><ChevronRight size={14} /></Link>; }

function InvoiceRow({ invoice, raw, selected }: { invoice: Invoice; raw: QueryRecord; selected: boolean }) {
  return <tr data-selected={selected ? "true" : "false"}><td><Link className={base.invoiceNumber} href={hrefWith(raw, { seleccion: invoice.id }, "directorio")}><strong>{invoice.invoiceNumber}</strong><small>{formatDate(invoice.issueDate)}</small></Link></td><td><Link href={`/subcontratas/${invoice.businessPartner.id}`}><strong>{invoice.businessPartner.commercialName}</strong><small>{invoice.businessPartner.taxId || "CIF/NIF pendiente"}</small></Link></td><td>{invoice.work ? <Link href={`/obras/${invoice.work.id}`}><strong>{invoice.work.titulo}</strong></Link> : <span className={base.muted}>Sin asignar</span>}</td><td><span className={styles.certification}>{certificationText(invoice.certifications, invoice.workDescription)}</span></td><td><strong>{formatCurrency(invoice.taxableBase)}</strong></td><td>{invoice.vatRate ?? "—"}%<small>{formatCurrency(invoice.vatAmount)}</small></td><td><ReviewBadge invoice={invoice} /></td><td>{invoice.withholdingRate ?? 0}%<small>{formatCurrency(invoice.withholdingAmount)}</small></td><td data-overdue={invoice.status === "OVERDUE"}>{formatDate(invoice.dueDate)}<small>{dueLabel(invoice)}</small></td><td><PaymentBadge invoice={invoice} /></td></tr>;
}
function MobileInvoice({ invoice, raw, selected }: { invoice: Invoice; raw: QueryRecord; selected: boolean }) { return <Link href={hrefWith(raw, { seleccion: invoice.id }, "directorio")} className={base.mobileInvoice} data-selected={selected ? "true" : "false"}><header><span><strong>{invoice.invoiceNumber}</strong><small>{invoice.businessPartner.commercialName}</small></span><ReviewBadge invoice={invoice} /></header><dl><div><dt>Proyecto</dt><dd>{invoice.work?.titulo ?? "Sin asignar"}</dd></div><div><dt>Certificación</dt><dd>{certificationText(invoice.certifications, invoice.workDescription)}</dd></div><div><dt>Total</dt><dd>{formatCurrency(invoice.total)}</dd></div><div><dt>Pago</dt><dd>{paymentLabel(invoice)}</dd></div></dl></Link>; }

function InvoiceDetail({ invoice, raw, panel, canPay }: { invoice: NonNullable<Awaited<ReturnType<typeof getPurchaseInvoiceDetail>>>; raw: QueryRecord; panel: string; canPay: boolean }) {
  const panelHref = (next: string) => hrefWith(raw, { seleccion: invoice.id, panel: next }, "directorio");
  const document = invoice.documents[0] ?? null;
  return <><header className={base.detailHeader}><div><strong>{invoice.invoiceNumber}</strong><ReviewBadge invoice={invoice} /></div><Link href="/facturas-subcontratas" aria-label="Cerrar detalle">×</Link></header><nav className={base.detailTabs} aria-label="Secciones del detalle"><Link href={panelHref("detalle")} aria-current={panel === "detalle" ? "page" : undefined}>Detalle</Link><Link href={panelHref("documento")} aria-current={panel === "documento" ? "page" : undefined}>Documento</Link><Link href={panelHref("historial")} aria-current={panel === "historial" ? "page" : undefined}>Actividad</Link></nav><div className={base.detailBody}>
    {panel === "detalle" ? <div className={base.detailGrid}><Info label="Subcontratista" value={invoice.businessPartner.commercialName} href={`/subcontratas/${invoice.businessPartner.id}`} /><Info label="Proyecto" value={invoice.work?.titulo || "Sin asignar"} href={invoice.work ? `/obras/${invoice.work.id}` : undefined} /><Info label="Certificación / partida" value={certificationText(invoice.certifications, invoice.workDescription)} /><Info label="Importe sin IVA" value={formatCurrency(invoice.taxableBase)} /><Info label="IVA" value={`${invoice.vatRate ?? "—"}% · ${formatCurrency(invoice.vatAmount)}`} /><Info label="Importe total" value={formatCurrency(invoice.total)} /><Info label="Retención fiscal" value={`${invoice.withholdingRate ?? 0}% · ${formatCurrency(invoice.withholdingAmount)}`} /><Info label="A pagar" value={formatCurrency(invoice.pendingAmount)} emphasis={invoice.pendingAmount > 0} /><Info label="Emisión" value={formatDate(invoice.issueDate)} /><Info label="Vencimiento" value={formatDate(invoice.dueDate)} emphasis={invoice.status === "OVERDUE"} /></div> : null}
    {panel === "documento" ? <div className={base.documentPanel}><div className={base.documentTitle}><FileText size={20} /><span><strong>{document?.name ?? "Sin documento adjunto"}</strong><small>{document ? "Documento vinculado a la factura" : "Pendiente de cargar desde la bandeja documental"}</small></span></div><div className={base.documentPreview}><span>FACTURA SUBCONTRATA</span><strong>{invoice.invoiceNumber}</strong><small>{invoice.businessPartner.commercialName}</small><dl><div><dt>Certificación</dt><dd>{certificationText(invoice.certifications, invoice.workDescription)}</dd></div><div><dt>Base</dt><dd>{formatCurrency(invoice.taxableBase)}</dd></div><div><dt>Total</dt><dd>{formatCurrency(invoice.total)}</dd></div></dl></div>{document?.storageKey ? <Link className={base.secondaryButton} href={`/gastos-materiales/lector/${document.id}/archivo`}>Abrir documento<ExternalLink size={13} /></Link> : <Link className={base.secondaryButton} href="/gastos-materiales/lector">Subir documento<Upload size={13} /></Link>}</div> : null}
    {panel === "historial" ? <ol className={base.history}>{invoice.history.length ? invoice.history.map((item) => <li key={item.id}><i /><div><strong>{item.detail}</strong><time dateTime={item.createdAt.toISOString()}>{formatDateTime(item.createdAt)}</time></div></li>) : <li><div><strong>Sin actividad registrada</strong><span>La trazabilidad aparecerá aquí.</span></div></li>}</ol> : null}
  </div><footer className={base.detailActions}><Link className={base.secondaryButton} href={`/facturas-subcontratas/${invoice.id}`}>Ficha completa</Link>{canPay && invoice.status !== "PAID" && invoice.status !== "VOID" ? <Link className={base.primaryButton} href={`/facturas-subcontratas/${invoice.id}#pago`}>Registrar pago</Link> : null}</footer></>;
}

function Info({ label, value, href, emphasis }: { label: string; value: string; href?: string; emphasis?: boolean }) { return <div className={base.info} data-emphasis={emphasis ? "true" : "false"}><span>{label}</span>{href ? <Link href={href}>{value}<ExternalLink size={10} /></Link> : <strong>{value}</strong>}</div>; }
function ReviewBadge({ invoice }: { invoice: Invoice }) { const data = reviewPresentation(invoice); return <span className={base.badge} data-tone={data.tone}>{data.label}</span>; }
function PaymentBadge({ invoice }: { invoice: Invoice }) { return <span className={base.paymentBadge} data-status={invoice.status}>{paymentLabel(invoice)}<small>{invoice.pendingAmount ? formatCurrency(invoice.pendingAmount) : "Sin pendiente"}</small></span>; }
function reviewPresentation(invoice: Invoice) { if (invoice.status === "VOID") return { label: "Anulada", tone: "neutral" }; if (!invoice.documents.length) return { label: "Pendiente de revisión", tone: "warning" }; if (!invoice.workId) return { label: "Sin proyecto", tone: "warning" }; return { label: "Revisada", tone: "success" }; }
function paymentLabel(invoice: Invoice) { return invoice.status === "PAID" ? "Pagada" : invoice.status === "OVERDUE" ? "Vencida" : invoice.status === "PARTIALLY_PAID" ? "Parcial" : invoice.status === "VOID" ? "Anulada" : "Pendiente"; }
function dueLabel(invoice: Invoice) { const days = Math.ceil((invoice.dueDate.getTime() - Date.now()) / 86400000); return invoice.status === "OVERDUE" ? "Vencida" : days === 0 ? "Hoy" : days > 0 ? `En ${days} días` : ""; }
function certificationText(value: unknown, fallback: string | null) { if (Array.isArray(value)) { const labels = value.map((item) => typeof item === "string" ? item : item && typeof item === "object" && "name" in item ? String((item as { name: unknown }).name) : "").filter(Boolean); if (labels.length) return labels.join(", "); } if (value && typeof value === "object") { const record = value as Record<string, unknown>; const label = record.name ?? record.label ?? record.reference; if (label) return String(label); } return fallback || "Sin certificación registrada"; }
function isUpcoming(invoice: Invoice) { const days = Math.ceil((invoice.dueDate.getTime() - Date.now()) / 86400000); return invoice.status !== "PAID" && invoice.status !== "VOID" && days >= 0 && days <= 7; }

function metricValues(invoices: Invoice[]) { const active = invoices.filter((invoice) => invoice.status !== "VOID"); const review = active.filter((invoice) => !invoice.documents.length); const reviewed = active.filter((invoice) => invoice.documents.length && invoice.workId); const pending = active.filter((invoice) => ["PENDING", "PARTIALLY_PAID", "OVERDUE"].includes(invoice.status)); const overdue = active.filter((invoice) => invoice.status === "OVERDUE"); const voided = invoices.filter((invoice) => invoice.status === "VOID"); const paidAll = active.filter((invoice) => invoice.status === "PAID"); const start = new Date(); start.setDate(1); start.setHours(0, 0, 0, 0); const month = active.filter((invoice) => invoice.issueDate >= start); const retained = active.filter((invoice) => invoice.withholdingAmount > 0); return { review: aggregate(review, "total"), reviewed: aggregate(reviewed, "total"), pending: aggregate(pending, "pendingAmount"), overdue: aggregate(overdue, "pendingAmount"), voided: aggregate(voided, "total"), paidAll: aggregate(paidAll, "total"), month: aggregate(month, "total"), retention: retained.reduce((sum, invoice) => sum + invoice.withholdingAmount, 0), retentionCount: retained.length }; }
function aggregate(items: Invoice[], field: "total" | "pendingAmount") { return { count: items.length, amount: items.reduce((sum, invoice) => sum + invoice[field], 0) }; }
function matches(invoice: Invoice, raw: QueryRecord) { const state = first(raw.estado) ?? "all"; if (state === "revision" && (invoice.documents.length || invoice.status === "VOID")) return false; if (state === "pendiente" && !["PENDING", "PARTIALLY_PAID", "OVERDUE"].includes(invoice.status)) return false; if (state === "revisada" && (!invoice.documents.length || !invoice.workId || invoice.status === "VOID")) return false; if (state === "anulada" && invoice.status !== "VOID") return false; if (state === "pagada" && invoice.status !== "PAID") return false; if (first(raw.sinObra) === "1" && invoice.workId) return false; if (first(raw.conDocumento) === "1" && !invoice.documents.length) return false; if (first(raw.retencion) === "1" && invoice.withholdingAmount <= 0) return false; const search = normalize(first(raw.buscar) ?? ""); return !search || normalize(`${invoice.invoiceNumber} ${invoice.description} ${invoice.businessPartner.commercialName} ${invoice.work?.titulo ?? ""} ${certificationText(invoice.certifications, invoice.workDescription)}`).includes(search); }
function normalize(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("es").trim(); }
function formatCurrency(value: number) { return new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(value); }
function formatDate(value: Date) { return new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "2-digit", year: "numeric" }).format(value); }
function formatDateTime(value: Date) { return new Intl.DateTimeFormat("es-ES", { dateStyle: "short", timeStyle: "short" }).format(value); }
function first(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
function numberValue(value: string | string[] | undefined, fallback: number) { const result = Number(first(value)); return Number.isFinite(result) ? result : fallback; }
function hrefWith(raw: QueryRecord, patch: Record<string, string | null>, hash?: string) { const params = new URLSearchParams(); for (const [key, value] of Object.entries(raw)) { const current = first(value); if (current) params.set(key, current); } for (const [key, value] of Object.entries(patch)) { if (value == null || value === "all") params.delete(key); else params.set(key, value); } const query = params.toString(); return `/facturas-subcontratas${query ? `?${query}` : ""}${hash ? `#${hash}` : ""}`; }
function exportHref(raw: QueryRecord) { const params = new URLSearchParams(); for (const key of ["estado", "sinObra", "conDocumento", "retencion", "buscar"]) { const value = first(raw[key]); if (value && value !== "all") params.set(key, value); } const query = params.toString(); return `/facturas-subcontratas/export${query ? `?${query}` : ""}`; }
