import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { MarketingPage, SectionIntro } from "@/components/marketing/marketing-shell";
import { planCatalog } from "@/lib/commercial/plans";

export const metadata: Metadata = { title: "Planes", description: "Conoce el catálogo de planes de Orqena y sus funcionalidades.", alternates: { canonical: "/planes" } };

const labels: Record<string, string> = { multi_company: "Multiempresa", advanced_permissions: "Permisos avanzados", team_management: "Gestión de equipo", team_scopes: "Alcances por equipo", orqena_chat: "Consultas con Orqena", orqena_actions: "Acciones con Orqena", orqena_memory: "Memoria de negocio", exports: "Exportaciones", automations: "Automatizaciones", audit_log: "Registro de auditoría", document_extraction: "Extracción documental", advanced_reports: "Informes avanzados", priority_support: "Soporte prioritario", api_access: "Acceso API", custom_roles: "Configuración avanzada de roles" };

export default function PlansPage() { return <MarketingPage><section className="marketing-container py-14 lg:py-24"><SectionIntro centered eyebrow="Planes" title="Un catálogo real, explicado sin inventar condiciones." description="Los planes recogen las funcionalidades previstas para cada etapa. Las condiciones comerciales se compartirán en una conversación adaptada a cada empresa." /><div className="mt-12 grid gap-4 lg:grid-cols-4">{Object.entries(planCatalog).map(([key, plan]) => { const features = Object.entries(plan.entitlements).filter(([, value]) => value === true).map(([name]) => labels[name]).filter(Boolean).slice(0, 6); return <article key={key} className="marketing-plan-card"><p className="marketing-eyebrow">{key}</p><h2>{plan.name}</h2><p className="mt-3 text-sm leading-6 text-content-secondary">{plan.audience}</p><p className="mt-6 border-y border-[#d9dfd4] py-4 text-sm font-semibold text-[#0d5b51]">Condiciones comerciales bajo consulta</p><ul className="mt-6 space-y-3">{features.map(feature => <li key={feature} className="flex gap-2 text-sm"><Check size={17} className="shrink-0 text-[#167366]" />{feature}</li>)}</ul><Link href="/demo" className="marketing-outline-button mt-8 w-full">Hablar de {plan.name} <ArrowRight size={16} /></Link></article>; })}</div></section><section className="border-t border-[#d9dfd4] bg-[#f4f1e8]"><div className="marketing-container py-16 text-center"><h2 className="marketing-title mx-auto max-w-2xl">La elección empieza por entender cómo trabaja tu equipo.</h2><p className="marketing-lede mx-auto mt-5">Una demo permite identificar qué recorrido, control y capacidad encaja mejor con vuestra actividad.</p><Link className="marketing-button mt-8" href="/demo">Solicitar demo <ArrowRight size={18} /></Link></div></section></MarketingPage>; }
