import { randomUUID } from "node:crypto";
import { requireAuthenticatedUser } from "@/lib/auth/session";
import { sectorProfiles } from "@/lib/business-profile/sectors";
import { createCompanyAction } from "./actions";

export default async function CreateCompanyPage() {
  await requireAuthenticatedUser();
  return <main className="screen mx-auto max-w-3xl py-10"><p className="type-label">Nuevo espacio</p><h1 className="type-page-title mt-2">Crea una empresa en Orqena</h1><p className="type-secondary mt-2">Empieza con lo esencial. Los datos fiscales pueden completarse después.</p><form action={createCompanyAction} className="card mt-6 grid gap-4 p-5 sm:grid-cols-2"><input type="hidden" name="idempotencyKey" value={randomUUID()}/><label className="sm:col-span-2"><span className="label">Nombre de la empresa o profesional</span><input required name="name" className="field mt-1"/></label><label><span className="label">Tipo</span><select name="organizationType" className="field mt-1"><option value="SELF_EMPLOYED">Autónomo</option><option value="COMPANY">Empresa</option></select></label><label><span className="label">Sector</span><select name="sectorKey" className="field mt-1">{Object.values(sectorProfiles).map((sector)=><option key={sector.key} value={sector.key}>{sector.name}</option>)}</select></label><label><span className="label">País</span><input name="country" defaultValue="España" className="field mt-1"/></label><label><span className="label">Tamaño del equipo</span><select name="teamSize" className="field mt-1"><option value="1">Solo yo</option><option value="2-5">2–5</option><option value="6-20">6–20</option><option value="21+">Más de 20</option></select></label><label className="sm:col-span-2"><span className="label">Objetivo principal</span><input name="mainGoal" className="field mt-1" placeholder="Ej. coordinar equipo y controlar cobros"/></label><div className="sm:col-span-2 flex justify-end"><button className="primary-button">Crear y continuar</button></div></form></main>;
}
