"use server";
import { revalidatePath } from "next/cache";
import { createOpaqueToken, hashToken, normalizeEmail } from "@/lib/auth/crypto";
import { prisma } from "@/lib/prisma";
import { requireCapability } from "@/lib/commercial/authorization";
import type { CompanyRole } from "@prisma/client";
import { capabilityCatalog, type CapabilityKey } from "@/lib/commercial/catalog";
import { canHoldEconomicCapabilities, ECONOMIC_CAPABILITIES, functionalProfileKeys, resolveFunctionalProfile, type FunctionalProfileKey } from "@/lib/commercial/functional-profiles";

const roles: CompanyRole[] = ["OWNER", "ADMIN", "MANAGER", "MEMBER", "VIEWER"];
export async function inviteMember(formData: FormData) {
  const auth = await requireCapability("company.members.invite"); const email = normalizeEmail(String(formData.get("email") ?? "")); const role = String(formData.get("role") ?? "MEMBER") as CompanyRole;
  if (!/^\S+@\S+\.\S+$/.test(email) || !roles.includes(role) || (role === "OWNER" && auth.role !== "OWNER")) throw new Error("INVITATION_INVALID");
  const rawToken = createOpaqueToken(); const now = new Date();
  await prisma.$transaction(async (tx) => { const duplicate = await tx.companyMembership.findFirst({ where: { companyId: auth.companyId, user: { emailNormalized: email }, status: { in: ["active", "invited"] } } }); if (duplicate) throw new Error("MEMBERSHIP_EXISTS"); await tx.invitation.updateMany({ where: { companyId: auth.companyId, emailNormalized: email, status: "PENDING" }, data: { status: "REVOKED", revokedAt: now } }); const invitation = await tx.invitation.create({ data: { companyId: auth.companyId, emailNormalized: email, role, inviterId: auth.userId, tokenHash: hashToken(rawToken), expiresAt: new Date(now.getTime() + 7 * 86_400_000) } }); await tx.auditLog.create({ data: { companyId: auth.companyId, userActorId: auth.userId, action: "invitation.created", targetType: "Invitation", targetId: invitation.id, metadata: { role } } }); });
  revalidatePath("/equipo");
}
export async function changeMemberRole(formData: FormData) { const auth = await requireCapability("company.members.update"); const membershipId = String(formData.get("membershipId") ?? ""); const role = String(formData.get("role") ?? "") as CompanyRole; if (!roles.includes(role) || role === "OWNER") throw new Error("ROLE_INVALID"); await prisma.$transaction(async(tx)=>{ const target=await tx.companyMembership.findFirstOrThrow({where:{id:membershipId,companyId:auth.companyId,status:"active"}}); if(target.userId===auth.userId) throw new Error("SELF_ELEVATION_FORBIDDEN"); if(target.role==="OWNER") throw new Error("OWNER_TRANSFER_REQUIRED"); await tx.companyMembership.update({where:{id:target.id},data:{role}}); await tx.auditLog.create({data:{companyId:auth.companyId,userActorId:auth.userId,action:"membership.role_changed",targetType:"CompanyMembership",targetId:target.id,metadata:{from:target.role,to:role}}});}); revalidatePath("/equipo"); }
export async function changeFunctionalProfile(formData: FormData) { const auth=await requireCapability("company.members.update");if(auth.role!=="OWNER")throw new Error("OWNER_REQUIRED");const membershipId=String(formData.get("membershipId")??"");const profile=String(formData.get("functionalProfileKey")??"") as FunctionalProfileKey;if(!functionalProfileKeys.includes(profile)||profile==="OWNER")throw new Error("PROFILE_INVALID");await prisma.$transaction(async tx=>{const target=await tx.companyMembership.findFirstOrThrow({where:{id:membershipId,companyId:auth.companyId,status:"active"}});if(target.userId===auth.userId||target.role==="OWNER")throw new Error("SELF_ELEVATION_FORBIDDEN");await tx.companyMembership.update({where:{id:target.id},data:{functionalProfileKey:profile}});await tx.auditLog.create({data:{companyId:auth.companyId,userActorId:auth.userId,action:"membership.functional_profile_changed",targetType:"CompanyMembership",targetId:target.id,metadata:{profile}}});});revalidatePath("/equipo");}
export async function transferOwnership(formData: FormData) { const auth=await requireCapability("company.members.remove"); if(auth.role!=="OWNER"||String(formData.get("confirm"))!=="TRANSFERIR") throw new Error("OWNER_CONFIRMATION_REQUIRED"); const membershipId=String(formData.get("membershipId")??""); const previousRole=String(formData.get("previousOwnerRole")??"ADMIN") as CompanyRole; await prisma.$transaction(async(tx)=>{ const target=await tx.companyMembership.findFirstOrThrow({where:{id:membershipId,companyId:auth.companyId,status:"active"}}); const current=await tx.companyMembership.findUniqueOrThrow({where:{id:auth.membershipId}}); await tx.companyMembership.update({where:{id:target.id},data:{role:"OWNER"}}); await tx.companyMembership.update({where:{id:current.id},data:{role:previousRole==="OWNER"?"ADMIN":previousRole}}); await tx.session.updateMany({where:{userId:{in:[target.userId,current.userId]},revokedAt:null},data:{revokedAt:new Date()}}); await tx.auditLog.create({data:{companyId:auth.companyId,userActorId:auth.userId,action:"ownership.transferred",targetType:"CompanyMembership",targetId:target.id,metadata:{previousOwnerMembershipId:current.id}}});}); }
export async function setPermissionOverride(formData:FormData){const auth=await requireCapability("company.members.update");const membershipId=String(formData.get("membershipId")??"");const capabilityKey=String(formData.get("capabilityKey")??"") as CapabilityKey;const effect=String(formData.get("effect")??"");if(!(capabilityKey in capabilityCatalog)||!["GRANT","DENY","ROLE"].includes(effect))throw new Error("PERMISSION_OVERRIDE_INVALID");const target=await prisma.companyMembership.findFirst({where:{id:membershipId,companyId:auth.companyId,status:"active"}});if(!target||target.userId===auth.userId)throw new Error("SELF_ELEVATION_FORBIDDEN");const profile=resolveFunctionalProfile(target.functionalProfileKey,target.role);if(effect==="GRANT"&&ECONOMIC_CAPABILITIES.has(capabilityKey)&&!canHoldEconomicCapabilities(profile))throw new Error("ECONOMIC_BOUNDARY_RESERVED");await prisma.$transaction(async tx=>{if(effect==="ROLE")await tx.membershipPermissionOverride.deleteMany({where:{membershipId,capabilityKey}});else await tx.membershipPermissionOverride.upsert({where:{membershipId_capabilityKey:{membershipId,capabilityKey}},update:{effect:effect as "GRANT"|"DENY",changedById:auth.userId,reason:"Cambio confirmado desde gestión de equipo"},create:{membershipId,capabilityKey,effect:effect as "GRANT"|"DENY",changedById:auth.userId,reason:"Cambio confirmado desde gestión de equipo"}});await tx.auditLog.create({data:{companyId:auth.companyId,userActorId:auth.userId,action:"membership.permission_changed",targetType:"CompanyMembership",targetId:membershipId,metadata:{capabilityKey,effect}}})});revalidatePath("/equipo")}
