import { requireCapability } from "@/lib/commercial/authorization";
import { capabilityCatalog } from "@/lib/commercial/catalog";
import { prisma } from "@/lib/prisma";
import { inviteMember, changeMemberRole, transferOwnership, setPermissionOverride } from "./actions";
// Responsive permission controls collapse before the md:grid-cols breakpoint.

export default async function TeamPage() {
  const auth = await requireCapability("company.members.view");
  const [members, invitations] = await Promise.all([
    prisma.companyMembership.findMany({ where: { companyId: auth.companyId }, include: { user: true, teamMemberships: { include: { team: true } }, permissionOverrides: true }, orderBy: { createdAt: "asc" } }),
    prisma.invitation.findMany({ where: { companyId: auth.companyId, status: "PENDING" }, orderBy: { createdAt: "desc" } })
  ]);
  return <main className="screen"><header><p className="type-label">Configuración</p><h1 className="type-page-title mt-2">Equipo y permisos</h1><p className="type-secondary mt-2">Roles, permisos efectivos e invitaciones de {auth.companyName}.</p></header>
    <section className="card mt-6 p-4"><h2 className="type-section-title">Invitar a una persona</h2><form action={inviteMember} className="mt-4 grid gap-3 sm:grid-cols-[1fr_12rem_auto]"><input required type="email" name="email" aria-label="Correo" className="field" placeholder="persona@empresa.es"/><select name="role" aria-label="Rol" className="field"><option>MEMBER</option><option>VIEWER</option><option>MANAGER</option><option>ADMIN</option></select><button className="primary-button">Crear invitación</button></form><p className="type-secondary mt-2">El adaptador local no envía correos reales.</p></section>
    <section className="mt-6"><h2 className="type-section-title">Miembros</h2><div className="mt-3 grid gap-3">{members.map(m=><article key={m.id} className="card p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><strong>{m.user.displayName}</strong><p className="type-secondary">{m.user.email} · {m.status} · {m.role}</p><p className="mt-1 text-xs text-content-tertiary">{m.teamMemberships.map(t=>t.team.name).join(", ")||"Sin equipo"} · {m.permissionOverrides.length} overrides</p></div>{m.role!=="OWNER"?<div className="flex flex-wrap gap-2"><form action={changeMemberRole} className="flex gap-2"><input type="hidden" name="membershipId" value={m.id}/><select name="role" defaultValue={m.role} aria-label={`Rol de ${m.user.displayName}`} className="field h-10 py-1"><option>VIEWER</option><option>MEMBER</option><option>MANAGER</option><option>ADMIN</option></select><button className="secondary-button">Guardar</button></form>{auth.role==="OWNER"?<form action={transferOwnership}><input type="hidden" name="membershipId" value={m.id}/><input type="hidden" name="confirm" value="TRANSFERIR"/><button className="ghost-button">Transferir propiedad</button></form>:null}</div>:<span className="text-sm font-semibold text-brand-strong">Propietario</span>}</div>
      {m.userId!==auth.userId&&m.role!=="OWNER"?<details className="mt-4 border-t border-border pt-3"><summary className="cursor-pointer font-semibold">Permiso personalizado</summary><form action={setPermissionOverride} className="mt-3 grid gap-2 sm:grid-cols-[1fr_10rem_auto]"><input type="hidden" name="membershipId" value={m.id}/><select name="capabilityKey" aria-label="Capacidad" className="field">{Object.entries(capabilityCatalog).map(([key,item])=><option key={key} value={key}>{item.domain} · {item.description}</option>)}</select><select name="effect" aria-label="Efecto" className="field"><option value="ROLE">Heredado del rol</option><option value="GRANT">Conceder</option><option value="DENY">Denegar</option></select><button className="secondary-button">Aplicar</button></form></details>:null}</article>)}</div></section>
    <section className="mt-6"><h2 className="type-section-title">Invitaciones pendientes</h2><div className="mt-3 grid gap-2">{invitations.length?invitations.map(i=><div key={i.id} className="card p-4"><strong>{i.emailNormalized}</strong><p className="type-secondary">{i.role} · caduca {i.expiresAt.toLocaleDateString("es-ES")}</p></div>):<p className="empty-state">No hay invitaciones pendientes.</p>}</div></section>
  </main>;
}
