import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { MarketingPage } from "@/components/marketing/marketing-shell";

const sectorInfo = {
  construction: { title: "Construcción y obra", lead: "Coordina trabajo, equipo y avances con el contexto de cada obra.", labels: ["Jefe de obra", "Encargado", "Operario"], points: ["Planificación y tareas asignadas", "Avances, incidencias y documentos vinculados", "Seguimiento de clientes y trabajos"] },
  installations: { title: "Instalaciones y mantenimiento", lead: "Une avisos, planificación, técnicos y seguimiento de cada intervención.", labels: ["Responsable de instalación", "Coordinador", "Técnico"], points: ["Agenda contextual para intervenciones", "Trabajos y archivos asignados", "Continuidad entre oficina y campo"] },
  "professional-services": { title: "Servicios profesionales", lead: "Mantén conectados clientes, proyectos, entregas y la actividad de tu equipo.", labels: ["Responsable de proyecto", "Coordinador", "Profesional"], points: ["Clientes y proyectos en contexto", "Seguimientos, agenda y documentos", "Visibilidad según la responsabilidad"] },
  "repair-workshop": { title: "Taller y reparación", lead: "Da continuidad a órdenes, recepción, operaciones y comunicación con clientes.", labels: ["Jefe de taller", "Encargado", "Técnico"], points: ["Trabajos y avances claros", "Tareas y archivos vinculados", "Actividad trazable por cliente"] },
  hospitality: { title: "Hostelería y servicios", lead: "Coordina el servicio, el equipo y las tareas con una visión compartida del día.", labels: ["Responsable de servicio", "Supervisor", "Empleado"], points: ["Plan diario y equipo", "Incidencias y tareas operativas", "Agenda que acompaña el servicio"] },
} as const;

type Sector = keyof typeof sectorInfo;
export function generateStaticParams() { return Object.keys(sectorInfo).map(sector => ({ sector })); }
export async function generateMetadata({ params }: { params: Promise<{ sector: string }> }): Promise<Metadata> { const { sector } = await params; const item = sectorInfo[sector as Sector]; return item ? { title: item.title, description: item.lead, alternates: { canonical: `/sectores/${sector}` } } : {}; }
export default async function SectorPage({ params }: { params: Promise<{ sector: string }> }) { const { sector } = await params; const item = sectorInfo[sector as Sector]; if (!item) notFound(); return <MarketingPage><section className="marketing-container grid gap-10 py-14 lg:grid-cols-[1fr_.8fr] lg:py-24"><div><p className="marketing-eyebrow">Sectores / {item.title}</p><h1 className="marketing-display mt-4">{item.title}</h1><p className="marketing-lede mt-5">{item.lead}</p><Link href="/demo" className="marketing-button mt-8">Hablar sobre mi equipo <ArrowRight size={18} /></Link></div><aside className="rounded-[2rem] bg-[#e7f0ea] p-7 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#167366]">Nombres cercanos</p><div className="mt-6 space-y-3">{item.labels.map((label, index) => <div key={label} className="flex items-center gap-4 rounded-xl bg-white px-4 py-3"><span className="text-sm font-black text-[#167366]">0{index + 1}</span><strong>{label}</strong></div>)}</div></aside></section><section className="border-y border-[#d9dfd4] bg-[#f4f1e8]"><div className="marketing-container py-16"><h2 className="marketing-title max-w-2xl">Una experiencia conectada a la forma de trabajar de tu actividad.</h2><ul className="mt-9 grid gap-4 md:grid-cols-3">{item.points.map(point => <li key={point} className="rounded-2xl bg-[#fbfaf5] p-5 text-sm leading-6"><Check className="mb-4 text-[#167366]" size={20} />{point}</li>)}</ul></div></section></MarketingPage>; }
