import type { ReactNode } from "react";
import Link from "next/link";
import { AlertTriangle, CheckCircle2, Download, RefreshCw, Trash2 } from "lucide-react";
import { notFound } from "next/navigation";
import { deleteExpenseDocument, findDuplicateExpenseDocumentIds, retryExpenseDocumentExtraction, saveExpenseFromDocument } from "@/app/(app)/gastos-materiales/actions";
import { SectionHeader } from "@/components/section-header";
import { requireCapability } from "@/lib/commercial/authorization";
import { categoryForDocument, EXPENSE_DOCUMENT_TYPES, normalizeExpenseExtraction } from "@/lib/expense-document";
import { formatCurrency } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export default async function ExpenseDocumentReviewPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; saved?: string; invoice?: string }> }) {
  const [{ id }, query, context] = await Promise.all([params, searchParams, requireCapability("purchases.received_invoices.view")]);
  const [document, works, clients, partners] = await Promise.all([
    prisma.document.findFirst({ where: { id, companyId: context.companyId, archivedAt: null }, include: { expense: true } }),
    prisma.work.findMany({ where: { companyId: context.companyId, archivada: false }, orderBy: { titulo: "asc" }, select: { id: true, titulo: true, clienteId: true } }),
    prisma.client.findMany({ where: { companyId: context.companyId, archivadoAt: null }, orderBy: { nombre: "asc" }, select: { id: true, nombre: true } }),
    prisma.businessPartner.findMany({ where: { companyId: context.companyId, archivedAt: null, status: { not: "BLOCKED" } }, orderBy: { commercialName: "asc" }, select: { id: true, commercialName: true, kind: true, taxId: true } })
  ]);
  if (!document) notFound();
  const proposal = normalizeExpenseExtraction(document.extractedData);
  const duplicateIds = await findDuplicateExpenseDocumentIds({ excludeDocumentId: document.id, sha256: document.sha256, invoiceNumber: proposal.invoiceNumber, issuerName: proposal.issuerName, issuerTaxId: proposal.issuerTaxId, issueDate: proposal.issueDate, total: proposal.total });
  const duplicates = duplicateIds.length ? await prisma.document.findMany({ where: { companyId: context.companyId, id: { in: duplicateIds } }, select: { id: true, name: true, extractedTotal: true } }) : [];
  const saved = Boolean(document.expenseId);
  return <main className="screen">
    <SectionHeader title="Revisar justificante" description={document.name} action={<Link href="/gastos-materiales/lector" className="secondary-button">Volver</Link>} />
    {query.error ? <ErrorNotice code={query.error} /> : null}
    {query.saved || saved ? <div className="mb-4 flex gap-3 rounded-xl border border-green-200 bg-green-50 p-4 text-green-900"><CheckCircle2 className="shrink-0" /><div><p className="font-black">Documento registrado</p><p className="mt-1 text-sm">El documento quedó enlazado al gasto{query.invoice ? " y a la factura recibida" : ""}; no se volverá a crear automáticamente.</p>{query.invoice ? <Link className="mt-2 inline-block font-bold underline" href={`${document.documentType === "SUBCONTRACTOR_INVOICE" ? "/facturas-subcontratas" : "/facturas-proveedor"}/${query.invoice}`}>Abrir factura recibida</Link> : null}</div></div> : null}
    {document.extractionError ? <div role="status" className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><p className="font-black">Revisión manual disponible</p><p className="mt-1">{document.extractionError}</p></div> : null}
    {proposal.warnings.length ? <div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-black text-amber-900">Campos que requieren atención</p><ul className="mt-2 list-disc pl-5 text-sm text-amber-900">{proposal.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div> : null}
    {duplicates.length ? <div className="mb-4 rounded-xl border border-orange-300 bg-orange-50 p-4"><div className="flex gap-2"><AlertTriangle className="shrink-0 text-orange-700" /><div><p className="font-black text-orange-900">Posible duplicado</p><p className="mt-1 text-sm text-orange-900">Se encontraron {duplicates.length} coincidencias dentro de esta empresa.</p></div></div><div className="mt-3 flex flex-wrap gap-2">{duplicates.map((item) => <Link className="secondary-button" href={`/gastos-materiales/lector/${item.id}`} key={item.id}>{item.name}{item.extractedTotal != null ? ` · ${formatCurrency(item.extractedTotal)}` : ""}</Link>)}</div></div> : null}

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]">
      <form action={saveExpenseFromDocument} className="card grid gap-5 p-4 sm:p-6">
        <input type="hidden" name="documentId" value={document.id} /><input type="hidden" name="confirmed" value="yes" />
        <fieldset disabled={saved} className="grid gap-5">
          <div className="grid gap-4 md:grid-cols-2"><Field label="Tipo de documento" confidence={proposal.fieldConfidence.documentType}><select className="field" name="documentType" defaultValue={document.documentType || proposal.documentType}>{EXPENSE_DOCUMENT_TYPES.map((type) => <option key={type} value={type}>{documentTypeLabel(type)}</option>)}</select></Field><Field label="Proveedor / emisor" confidence={proposal.fieldConfidence.issuerName} required><input className="field" name="issuerName" defaultValue={proposal.issuerName || ""} placeholder="Introduce el proveedor" /></Field></div>
          <div className="grid gap-4 md:grid-cols-2"><Field label="NIF / CIF / VAT" confidence={proposal.fieldConfidence.issuerTaxId}><input className="field" name="issuerTaxId" defaultValue={proposal.issuerTaxId || ""} /></Field><Field label="Número de factura o ticket" confidence={proposal.fieldConfidence.invoiceNumber}><input className="field" name="invoiceNumber" defaultValue={proposal.invoiceNumber || ""} /></Field></div>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Fecha" confidence={proposal.fieldConfidence.issueDate} required missing={!proposal.issueDate}><input className="field" required type="date" name="issueDate" defaultValue={proposal.issueDate || ""} /></Field><Field label="Vencimiento" confidence={proposal.fieldConfidence.dueDate}><input className="field" type="date" name="dueDate" defaultValue={proposal.dueDate || ""} /></Field><Field label="Base imponible" confidence={proposal.fieldConfidence.taxableBase}><input className="field" inputMode="decimal" name="taxableBase" defaultValue={proposal.taxableBase ?? ""} /></Field><Field label="IVA" confidence={proposal.fieldConfidence.vatAmount}><input className="field" inputMode="decimal" name="vatAmount" defaultValue={proposal.vatAmount ?? ""} /></Field></div>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="IVA %"><input className="field" inputMode="decimal" name="vatRate" defaultValue={proposal.vatRate ?? ""} /></Field><Field label="IRPF" confidence={proposal.fieldConfidence.withholdingAmount}><input className="field" inputMode="decimal" name="withholdingAmount" defaultValue={proposal.withholdingAmount ?? ""} /></Field><Field label="Tipo fiscal"><select className="field" name="fiscalType" defaultValue="FULL_INVOICE"><option value="FULL_INVOICE">Factura completa</option><option value="SIMPLIFIED_INVOICE">Factura simplificada</option><option value="CORRECTIVE_INVOICE">Factura rectificativa</option></select></Field><Field label="Total" confidence={proposal.fieldConfidence.total} required missing={proposal.total == null}><input className="field" required inputMode="decimal" name="total" defaultValue={proposal.total ?? ""} /></Field></div>
          <div className="grid gap-4 md:grid-cols-2"><Field label="Método de pago" confidence={proposal.fieldConfidence.paymentMethod}><input className="field" name="paymentMethod" defaultValue={proposal.paymentMethod || ""} /></Field><Field label="Proveedor / subcontrata"><select className="field" name="businessPartnerId" defaultValue={document.businessPartnerId || ""}><option value="">Sin ficha vinculada</option>{partners.map((partner) => <option key={partner.id} value={partner.id}>{partner.commercialName} · {partner.kind === "SUBCONTRACTOR" ? "Subcontrata" : "Proveedor"}{partner.taxId ? ` · ${partner.taxId}` : ""}</option>)}</select><Link className="mt-2 inline-block text-xs font-bold underline" href="/proveedores?nuevo=1#ficha">Crear proveedor</Link><span className="mx-2 text-slate-300">·</span><Link className="text-xs font-bold underline" href="/subcontratas?nuevo=1#ficha">Crear subcontrata</Link></Field></div>
          <div className="grid gap-4 md:grid-cols-2"><Field label="Categoría" confidence={proposal.fieldConfidence.suggestedCategory}><select className="field" name="category" defaultValue={categoryForDocument(proposal.documentType, proposal.suggestedCategory)}><option value="materiales">Materiales</option><option value="combustible">Combustible</option><option value="restauracion">Restauración</option><option value="herramientas">Herramientas</option><option value="maquinaria">Maquinaria</option><option value="transportes">Transportes</option><option value="subcontrata">Subcontratas</option><option value="servicios">Servicios</option><option value="suministros">Suministros</option><option value="otros">Otros</option></select></Field><Field label="Descripción" confidence={proposal.fieldConfidence.description} required><input className="field" name="description" required defaultValue={proposal.description || ""} placeholder="Concepto del gasto" /></Field></div>
          <div className="grid gap-4 md:grid-cols-2"><Field label="Obra (opcional)"><select className="field" name="obraId" defaultValue={document.workId || ""}><option value="">Gasto general, sin obra</option>{works.map((work) => <option key={work.id} value={work.id}>{work.titulo}</option>)}</select></Field><Field label="Cliente (opcional)"><select className="field" name="clienteId" defaultValue={document.clientId || ""}><option value="">Sin cliente</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.nombre}</option>)}</select></Field></div>
          <Field label="Notas internas"><textarea className="field min-h-24" name="notes" placeholder="Solo visibles dentro de Orqena" /></Field>
          {proposal.lines.length ? <Field label="Líneas detectadas (editables)"><textarea className="field min-h-32" name="linesReview" defaultValue={proposal.lines.map((line) => line.description).join("\n")} aria-describedby="lines-help" /><span id="lines-help" className="text-xs text-slate-500">Una línea por concepto. Los importes detectados se conservan mientras no elimines la línea.</span><div className="grid gap-2">{proposal.lines.map((line, index) => <div key={`${line.description}-${index}`} className="rounded-lg border border-slate-200 p-3 text-sm"><p className="font-bold">{line.description}</p><p className="mt-1 text-slate-500">{line.quantity ?? "—"} × {line.unitPrice == null ? "—" : formatCurrency(line.unitPrice)} · {line.total == null ? "—" : formatCurrency(line.total)}</p></div>)}</div></Field> : null}
          {duplicates.length ? <label className="flex items-start gap-3 rounded-xl border border-orange-300 p-4 text-sm"><input className="mt-1" type="checkbox" name="confirmDuplicate" value="yes" /><span><strong>Confirmo que he revisado el posible duplicado</strong><br />Quiero crear el gasto de todos modos.</span></label> : null}
          <button className="primary-button w-full justify-center sm:w-auto" type="submit">Guardar como gasto</button>
        </fieldset>
      </form>

      <aside className="grid content-start gap-3">
        <div className="card p-4"><p className="text-sm font-black text-obra-ink">Documento original</p><p className="mt-2 break-words text-sm text-slate-600">{document.originalName}</p><p className="mt-1 text-xs text-slate-500">{Math.ceil((document.size || 0) / 1024)} KB · {document.mimeType}</p><Link href={`/gastos-materiales/lector/${document.id}/archivo`} target="_blank" className="secondary-button mt-3 w-full justify-center"><Download size={18} /> Abrir documento</Link></div>
        <div className="card p-4"><p className="text-sm font-black text-obra-ink">Origen de los datos</p><p className="mt-2 text-sm text-slate-600">{document.extractionStatus === "COMPLETED" ? `Propuesta automática · confianza ${Math.round((document.extractionConfidence || 0) * 100)} %` : "Entrada manual"}</p><p className="mt-2 text-xs text-slate-500">Los campos con confianza baja se marcan en ámbar. Cualquier cambio del usuario prevalece.</p><form action={retryExpenseDocumentExtraction} className="mt-3"><input type="hidden" name="id" value={document.id} /><button className="secondary-button w-full justify-center" type="submit"><RefreshCw size={17} /> Reintentar análisis</button></form></div>
        <form action={deleteExpenseDocument} className="card p-4"><input type="hidden" name="id" value={document.id} />{saved ? <label className="mb-3 flex items-start gap-2 text-xs text-slate-600"><input className="mt-1" type="checkbox" name="confirmLinked" value="yes" />Eliminar solo el documento y conservar el gasto enlazado.</label> : null}<button className="secondary-button w-full justify-center text-red-700" type="submit"><Trash2 size={17} /> Eliminar documento</button></form>
      </aside>
    </div>
  </main>;
}

function Field({ label, confidence, required, missing, children }: { label: string; confidence?: number; required?: boolean; missing?: boolean; children: ReactNode }) { const low = confidence != null && confidence < 0.65; return <label className={`grid gap-2 rounded-xl ${low || missing ? "bg-amber-50 p-3 ring-1 ring-amber-200" : ""}`}><span className="flex flex-wrap items-center gap-2 text-sm font-black text-obra-ink">{label}{required ? <span className="text-red-700">Obligatorio</span> : null}{low ? <span className="rounded bg-amber-200 px-2 py-0.5 text-xs text-amber-900">Confianza baja</span> : confidence != null ? <span className="text-xs font-semibold text-slate-400">Leído automáticamente</span> : null}</span>{children}</label>; }
function documentTypeLabel(type: string) { return ({ MATERIAL_INVOICE: "Factura de materiales", FUEL_RECEIPT: "Ticket de combustible", MEAL_RECEIPT: "Restauración", TOOL_INVOICE: "Herramientas", MACHINERY_INVOICE: "Maquinaria", TRANSPORT_INVOICE: "Transportes", SUBCONTRACTOR_INVOICE: "Factura de subcontrata", SERVICE_INVOICE: "Servicios", SUPPLY_INVOICE: "Suministros", GENERAL_EXPENSE: "Gasto general", UNKNOWN: "Sin clasificar" } as Record<string, string>)[type] || type; }
function ErrorNotice({ code }: { code: string }) { const message = ({ confirmation_required: "Debes confirmar expresamente la creación del gasto.", already_saved: "Este documento ya está enlazado a un gasto.", invalid_relation: "La obra o el cliente no pertenece a tu empresa, o la relación no es válida.", invalid_partner: "El proveedor está bloqueado, no existe o pertenece a otra empresa.", purchase_invoice_duplicate: "Esa factura ya está registrada para el mismo proveedor.", required_fields: "Revisa los campos obligatorios y sus formatos.", duplicate_confirmation_required: "Revisa el posible duplicado y marca la confirmación antes de continuar.", linked_confirmation_required: "Confirma que deseas eliminar el documento enlazado conservando el gasto." } as Record<string, string>)[code] || "No se pudo completar la operación."; return <div role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{message}</div>; }
